name: flutter_final_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Menggunakan rentang yang lebih aman

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9 # Tetap ada, mungkin dibutuhkan di tempat lain

  # Izin dan Suara
  permission_handler: ^11.0.0 # Upgrade ke versi major terbaru
  flutter_sound: ^9.2.13

  #tflite
  tflite_flutter: ^0.11.0

  # Untuk menampilkan peta
  flutter_map: ^6.1.0 
  # Untuk data latitude & longitude
  latlong2: ^0.9.0 
  # Untuk state management (mengelola lokasi pengguna)
  provider: ^6.1.5

  # --- TAMBAHKAN BARIS INI ---
  flutter_polyline_points: ^2.0.0
  # --------------------------------

  # --- TAMBAHKAN DUA BARIS INI ---
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  # ----------------

  #article
  http: ^1.2.1 # Untuk membuat request ke API
  url_launcher: ^6.2.6 # Untuk membuka link artikel di browser
  xml2json: ^6.1.1 

  # UI dan Utilitas
  image_picker: ^1.0.7
  image: ^4.1.3
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.19.0
  dotted_border: ^2.1.0
  cupertino_icons: ^1.0.8

  #Tambahkan dependensi di bawah ini
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0 # Untuk menyimpan API Key dengan aman

dependency_overrides:
  # Untuk mengatasi masalah build web, tidak akan mempengaruhi android
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Upgrade ke versi terbaru

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/family.png
    - .env
    - assets/model_gizi.tflite
    - assets/model (1).tflite