// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHQNEln4ep4-7yH36e2-9Bl3Dl6B71gM',
    appId: '1:519153859325:web:e942f09a4db7a153099c94',
    messagingSenderId: '519153859325',
    projectId: 'pantaunusaapp-bf2a8',
    authDomain: 'pantaunusaapp-bf2a8.firebaseapp.com',
    storageBucket: 'pantaunusaapp-bf2a8.firebasestorage.app',
    measurementId: 'G-N85ZT73DD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDaOXq9nVBKOD0ketYm4csMme3-ue_vw',
    appId: '1:519153859325:android:cfcc7303e9817b69099c94',
    messagingSenderId: '519153859325',
    projectId: 'pantaunusaapp-bf2a8',
    storageBucket: 'pantaunusaapp-bf2a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPcI9A-f2bR9kAB4bU9x3iXddvmR3KRR4',
    appId: '1:519153859325:ios:82d74803da2cd945099c94',
    messagingSenderId: '519153859325',
    projectId: 'pantaunusaapp-bf2a8',
    storageBucket: 'pantaunusaapp-bf2a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPcI9A-f2bR9kAB4bU9x3iXddvmR3KRR4',
    appId: '1:519153859325:ios:82d74803da2cd945099c94',
    messagingSenderId: '519153859325',
    projectId: 'pantaunusaapp-bf2a8',
    storageBucket: 'pantaunusaapp-bf2a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVHQNEln4ep4-7yH36e2-9Bl3Dl6B71gM',
    appId: '1:519153859325:web:2aa0fecf65f902ca099c94',
    messagingSenderId: '519153859325',
    projectId: 'pantaunusaapp-bf2a8',
    authDomain: 'pantaunusaapp-bf2a8.firebaseapp.com',
    storageBucket: 'pantaunusaapp-bf2a8.firebasestorage.app',
    measurementId: 'G-EKJDQ2W366',
  );

}